const PROFIT_RATE=0.05
const FEE_RATE=0.005
const TAX_RATE=0.005
const PRICE_CITY=10000
const PRICE_HOUSE=10

module.exports = [
  {
    pcode: 'LD',
    name: {zhCN:'伦敦'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+0'),
  },
  {
    pcode: 'MNH',
    name: {zhCN:'慕尼黑'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+1'),
  },
  {
    pcode: 'YSTBR',
    name: {zhCN:'伊斯坦布尔'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+2'),
  },
  {
    pcode: 'DHL',
    name: {zhCN:'德黑兰'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+3'),
  },
  {
    pcode: 'MSK',
    name: {zhCN:'莫斯科'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+4'),
  },
  {
    pcode: 'YSLB',
    name: {zhCN:'伊斯兰堡'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+5'),
  },
  {
    pcode: 'YG',
    name: {zhCN:'仰光'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+6'),
  },
  {
    pcode: 'XJP',
    name: {zhCN:'新加坡'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+7'),
  },
  {
    pcode: 'BJ',
    name: {zhCN:'北京'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+8'),
  },
  {
    pcode: 'DJ',
    name: {zhCN:'东京'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+9'),
  },
  {
    pcode: 'XN',
    name: {zhCN:'悉尼'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+10'),
  },
  {
    pcode: 'SLMQD',
    name: {zhCN:'所罗门群岛'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+11'),
  },
  {
    pcode: 'HLD',
    name: {zhCN:'惠灵顿'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+12'),
  },
  {
    pcode: 'ZTD',
    name: {zhCN:'中途岛'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-11'),
  },
  {
    pcode: 'XWYQD',
    name: {zhCN:'夏威夷群岛'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-10'),
  },
  {
    pcode: 'MKSSQD',
    name: {zhCN:'马克萨斯群岛'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-9'),
  },
  {
    pcode: 'WGH',
    name: {zhCN:'温哥华'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-8'),
  },
  {
    pcode: 'TPY',
    name: {zhCN:'太平洋'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-7'),
  },
  {
    pcode: 'ZJG',
    name: {zhCN:'芝加哥'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-6'),
  },
  {
    pcode: 'BSD',
    name: {zhCN:'波士顿'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-5'),
  },
  {
    pcode: 'SDYG',
    name: {zhCN:'圣地亚哥'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-4'),
  },
  {
    pcode: 'LYRNL',
    name: {zhCN:'里约热内卢'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-3'),
  },
  {
    pcode: 'YSRQD',
    name: {zhCN:'亚速尔群岛'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-2'),
  },
  {
    pcode: 'MDLQD',
    name: {zhCN:'马德拉群岛'},
    desc: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-1'),
  },
]
