const PROFIT_RATE=0.05
const FEE_RATE=0.005
const TAX_RATE=0.005
const PRICE_CITY=5000
const PRICE_HOUSE=10

module.exports = [
  {
    pcode: 'LD',
    name: { zhCN:'伦敦', enUS:'伦敦', native:'伦敦' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+0'),
  },
  {
    pcode: 'MNH',
    name: { zhCN:'慕尼黑', enUS:'慕尼黑', native:'慕尼黑' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+1'),
  },
  {
    pcode: 'YSTBR',
    name: { zhCN:'伊斯坦布尔', enUS:'伊斯坦布尔', native:'伊斯坦布尔' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+2'),
  },
  {
    pcode: 'DHL',
    name: { zhCN:'德黑兰', enUS:'德黑兰', native:'德黑兰' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+3'),
  },
  {
    pcode: 'MSK',
    name: { zhCN:'莫斯科', enUS:'莫斯科', native:'莫斯科' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+4'),
  },
  {
    pcode: 'YSLB',
    name: { zhCN:'伊斯兰堡', enUS:'伊斯兰堡', native:'伊斯兰堡' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+5'),
  },
  {
    pcode: 'YG',
    name: { zhCN:'仰光', enUS:'仰光', native:'仰光' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+6'),
  },
  {
    pcode: 'XJP',
    name: { zhCN:'新加坡', enUS:'新加坡', native:'新加坡' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+7'),
  },
  {
    pcode: 'BJ',
    name: { zhCN:'北京', enUS:'北京', native:'北京' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+8'),
  },
  {
    pcode: 'DJ',
    name: { zhCN:'东京', enUS:'东京', native:'东京' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+9'),
  },
  {
    pcode: 'XN',
    name: { zhCN:'悉尼', enUS:'悉尼', native:'悉尼' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+10'),
  },
  {
    pcode: 'SLMQD',
    name: { zhCN:'所罗门群岛', enUS:'所罗门群岛', native:'所罗门群岛' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+11'),
  },
  {
    pcode: 'HLD',
    name: { zhCN:'惠灵顿', enUS:'惠灵顿', native:'惠灵顿' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT+12'),
  },
  {
    pcode: 'ZTD',
    name: { zhCN:'中途岛', enUS:'中途岛', native:'中途岛' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-11'),
  },
  {
    pcode: 'XWYQD',
    name: { zhCN:'夏威夷群岛', enUS:'夏威夷群岛', native:'夏威夷群岛' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-10'),
  },
  {
    pcode: 'MKSSQD',
    name: { zhCN:'马克萨斯群岛', enUS:'马克萨斯群岛', native:'马克萨斯群岛' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-9'),
  },
  {
    pcode: 'WGH',
    name: { zhCN:'温哥华', enUS:'温哥华', native:'温哥华' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-8'),
  },
  {
    pcode: 'TPY',
    name: { zhCN:'太平洋', enUS:'太平洋', native:'太平洋' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-7'),
  },
  {
    pcode: 'ZJG',
    name: { zhCN:'芝加哥', enUS:'芝加哥', native:'芝加哥' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-6'),
  },
  {
    pcode: 'BSD',
    name: { zhCN:'波士顿', enUS:'波士顿', native:'波士顿' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-5'),
  },
  {
    pcode: 'SDYG',
    name: { zhCN:'圣地亚哥', enUS:'圣地亚哥', native:'圣地亚哥' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-4'),
  },
  {
    pcode: 'LYRNL',
    name: { zhCN:'里约热内卢', enUS:'里约热内卢', native:'里约热内卢' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-3'),
  },
  {
    pcode: 'YSRQD',
    name: { zhCN:'亚速尔群岛', enUS:'亚速尔群岛', native:'亚速尔群岛' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-2'),
  },
  {
    pcode: 'MDLQD',
    name: { zhCN:'马德拉群岛', enUS:'马德拉群岛', native:'马德拉群岛' },
    intro: '',
    amount: 1,
    profitRate: PROFIT_RATE,
    feeRate: FEE_RATE,
    taxRate: TAX_RATE,
    startPrice: PRICE_CITY,
    startTime: new Date('2019-12-31 12:00:00 GMT-1'),
  },
]
